### ISSUE TITLE
Whats about BibsOnGitLab?

### ISSUE THREAD

**Issue by leozachl** [hbunke/BibsOnGitHub#106]
do you want links to repos on gitlab too?

**Comment by stweil** [comment]
Good question. What do users think?

See also [related discussion](https://github.com/hbunke/BibsOnGitHub/pull/100#discussion_r825267740).

**Comment by stweil** [comment]
@leozachl, would you suggest a separate repository BibsOnGitLab, either here or on GitLab? Or a separate list in this repository? Or allow GitLab URLs in the current list, too.

**Comment by leozachl** [comment]
Only GitLab URLs in the current list.

**Comment by hbunke** [comment]
IMHO GitLab repos could be listed here as well. In the end it is all
about open/public library related git repos, independent of the
platform. When I started this repo back in 2015, GitLab didn't have
much significance yet. Actually I don't know how it is nowadays (I'd
assume that GitLab is more used internally), but I can't see any
reasons to exclude those repos here as long as they are public.

In terms of implementation, we should keep it simple: just put the
GitLab URL instead of the GitHub one, so no separate list or anything
like that.

regards
hendrik

On Mon, 2023-02-13 at 10:11 -0800, Stefan Weil wrote:
> @leozachl, would you suggest a separate repository BibsOnGitLab,
> either here or on GitLab? Or a separate list in this repository? Or
> allow GitLab URLs in the current list, too.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this
> thread.Message ID:
> ***@***.***>

-- 
Dr. Hendrik Bunke
http://hbxt.org

**Comment by stweil** [comment]
I just merged the first GitLab account for the library of TU Wien (which also has a GitHub account).

**Comment by stweil** [comment]
GitLab is now mentioned in the README, too. Therefore I close this issue.
